version: '3.1'
services:
  stats-server:
    build: ./statistics
    image: stats-image
    ports:
       - "9090:9090"
    depends_on:
        - stats-db
    environment:
       - spring.datasource.url=jdbc:postgresql://stats-db:5432/stats
       - SPRING_DATASOURCE_USERNAME=stats
       - SPRING_DATASOURCE_PASSWORD=password
    restart: always


  stats-db:
    image: postgres:14-alpine
    volumes:
       - /var/lib/postgresql/data/
    ports:
       - "6542:5432"
    environment:
       - POSTGRES_DB=stats
       - POSTGRES_USER=stats
       - POSTGRES_PASSWORD=password
    restart: always

  ewm-service:
    build: ./server
    image: server-image
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-db
    environment:
      - STATS_SERVER_URL=http://stats-server:9090
      - spring.datasource.url=jdbc:postgresql://ewm-db:5432/main
      - SPRING_DATASOURCE_USERNAME=main
      - SPRING_DATASOURCE_PASSWORD=password
    restart: always

  ewm-db:
    image: postgres:14-alpine
    volumes:
    - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=main
      - POSTGRES_PASSWORD=password
    restart: always